import 'package:flutter/material.dart';
import 'package:staff/custum/textcostom.dart';
import 'package:url_launcher/url_launcher.dart';

class Privacy_policy extends StatelessWidget {
  const Privacy_policy({super.key});

  @override
  Widget build(BuildContext context) {
    int a =8848561548;
    return  Scaffold(
      appBar: AppBar(
        foregroundColor: Colors.white,
        title: const Apptext("Privacy Policy", ),
        centerTitle: true,
        backgroundColor:  const Color.fromRGBO(22, 38, 52, 1),
      ),
      body:  const SingleChildScrollView(
        child: Padding(
          
          padding: EdgeInsets.only(left: 20,right: 20),
          child: Column(
            children: [
              SizedBox(height: 21,),
                   Row(
                    children: [
                         Apptext("Privacy Policy",fontSize: 23,Colors: Color.fromRGBO(0, 0, 0, 1), fontweight: FontWeight.bold,)
                    ],
                   )
                   ,SizedBox( height: 20,)
                  , Row(
                    children: [
                         Apptext("Last updated: September 14, 2024",fontSize:14,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
                    ],
                   ),
                   SizedBox(height: 20,)
                   ,Apptext('''This Privacy Policy describes Our policies and procedures on the collection,use and disclosure of Your information when You use the Service and tells Youabout Your privacy rights and how the law protects You.
         We use Your Personal data to provide and improve the Service. By using theService, You agree to the collection and use of information in accordance with this Privacy Policy.
         '''),
             SizedBox(height: 10,),
                 Row(
                    children: [
                         Apptext("Interpretation and Definitions",fontSize: 23,Colors: Color.fromRGBO(0, 0, 0, 1), fontweight: FontWeight.bold,)
                    ],
                   ),
                   SizedBox(height: 20,)
                    ,Row(
                    children: [
                         Apptext("Interpretation ",fontSize:20,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
                    ],
                   ),
                   SizedBox(height: 20,),
                   Apptext('''The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural. 
        ''')
                          ,Row(
                    children: [
                         Apptext("Definitions",fontSize:20,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
                    ],
                   ),
                   SizedBox(height: 20,),
                   Row(
                    children: [
                         Apptext("  For the purposes of this Privacy Policy:",fontSize:14,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
                    ],
                   ),
                   SizedBox( height: 10),
                Apptext('''* Account means a unique account  created for You to access our Service or parts of our Service.
          
 * Affiliate means an entity that controls, is controlled   by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
        
 * Application refers to staffsphear, the software program provided by the Company.staffsphear.
            
 * Country refers to: Kerala, India
        
 * Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
            
        
* Personal Data is any information that relates to an identified or  identifiable individual.
           
        
* Service refers to the Application.
        
* Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
        
* Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example,the duration of a page visit).
        
* You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.''')
 ,SizedBox(height: 20,),
  Row(
   children: [
            Apptext("collecting and Using Your Personal Data",fontSize: 18,Colors: Color.fromRGBO(0, 0, 0, 1), fontweight: FontWeight.bold,)
     ],
     ),
     SizedBox(height: 20,),
      Row(
     children: [
               Apptext("Use Data",fontSize:20,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
                    ],
                   ),
                   SizedBox(height: 20,),
                   Apptext('''Usage Data is collected automatically when using the Service.

Usage Data may include information such as Your Device's Internet Protocoladdress (e.g. IP address), browser type, browser version, the pages of ourService that You visit, the time and date of Your visit, the time spent onthose pages, unique device identifiers and other diagnostic data.

When You access the Service by or through a mobile device, We may collectcertain information automatically, including, but not limited to, the type ofmobile device You use, Your mobile device unique ID, the IP address of Yourmobile device, Your mobile operating system, the type of mobile Internetbrowser You use, unique device identifiers and other diagnostic data.

We may also collect information that Your browser sends whenever You visit ourService or when You access the Service by or through a mobile device.''')
,SizedBox(height: 20,),
 Row(
     children: [
               Apptext('''Information Collected while Using the
Application ''',fontSize: 18,Colors: Color.fromRGBO(0, 0, 0, 1), fontweight: FontWeight.bold,)
                    ],
                   ),
                     
                    SizedBox(height: 20),    
Apptext('''While using Our Application, in order to provide features of Our Application,We may collect, with Your prior permission:
''',fontSize:20,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w300,) ,SizedBox(height: 20,),
Apptext('''* Pictures and other information from your Device's camera and photo library

We use this information to provide features of Our Service, to improve andcustomize Our Service. The information may be uploaded to the Company'sservers and/or a Service Provider's server or it may be simply stored on Yourdevice.

You can enable or disable access to this information at any time, through YourDevice settings.''')
  ,SizedBox(height: 20,)
  ,Row(
     children: [
               Apptext('''Use of Your Personal Data   ''',fontSize: 18,Colors: Color.fromRGBO(0, 0, 0, 1), fontweight: FontWeight.bold,)
                    ],
                   ),
               SizedBox(height: 20,),
                         Apptext("The Company may use Personal Data for the following purposes:",fontSize:16,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
                   ,SizedBox(height: 20,)
                  ,Apptext('''* To provide and maintain our Service , including to monitor the usage of
    our Service.

* To manage Your Account: to manage Your registration as a user of theService. The Personal Data You provide can give You access to differentfunctionalities of the Service that are available to You as a registered user.

* For the performance of a contract: the development, compliance andundertaking of the purchase contract for the products, items or servicesYou have purchased or of any other contract with Us through the Service.

* To contact You: To contact You by email, telephone calls, SMS, or otherequivalent forms of electronic communication, such as a mobileapplication's push notifications regarding updates or informativecommunications related to the functionalities, products or contractedservices, including the security updates, when necessary or reasonable fortheir implementation.

* To provide You with news, special offers and general information aboutother goods, services and events which we offer that are similar to thosethat you have already purchased or enquired about unless You have opted not to receive such information.

* To manage Your requests: To attend and manage Your requests to Us.

* For business transfers: We may use Your information to evaluate or conducta merger, divestiture, restructuring, reorganization, dissolution, orother sale or transfer of some or all of Our assets, whether as a goingconcern or as part of bankruptcy, liquidation, or similar proceeding, inwhich Personal Data held by Us about our Service users is among the assetstransferred.

* For other purposes : We may use Your information for other purposes, suchas data analysis, identifying usage trends, determining the effectivenessof our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.
'''),
  SizedBox(height: 20,),
  Apptext("We may share Your personal information in the following situations:",fontSize:16,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
  ,SizedBox(height: 12,),
  Apptext('''* With Service Providers: We may share Your personal information withService Providers to monitor and analyze the use of our Service, to contact You.
* For business transfers: We may share or transfer Your personal informationin connection with, or during negotiations of, any merger, sale of Companyassets, financing, or acquisition of all or a portion of Our business to another company.
 
* With Affiliates: We may share Your information with Our affiliates, inwhich case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, jointventure partners or other companies that We control or that are under common control with Us.
 
* With business partners: We may share Your information with Our businesspartners to offer You certain products, services or promotions.
 
* With other users: when You share personal information or otherwiseinteract in the public areas with other users, such information may beviewed by all users and may be publicly distributed outside.
 
* With Your consent : We may disclose Your personal information for any other purpose with Your consent.''')
   ,SizedBox(height: 20,),
  Row(
    children: [ 
     
      Apptext("Retention of Your Personal Data:",fontSize:16,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
    ],
  ),
   
  SizedBox(height: 12,),
  Apptext('''The Company will retain Your Personal Data only for as long as is necessaryfor the purposes set out in this Privacy Policy. We will retain and use YourPersonal Data to the extent necessary to comply with our legal obligations(for example, if we are required to retain your data to comply with applicablelaws), resolve disputes, and enforce our legal agreements and policies.

The Company will also retain Usage Data for internal analysis purposes. UsageData is generally retained for a shorter period of time, except when this datais used to strengthen the security or to improve the functionality of OurService, or We are legally obligated to retain this data for longer timeperiods.''')

,SizedBox(height: 20,)
  ,Row(
    children: [ 
     
      Apptext("Transfer of Your Personal Data :",fontSize:16,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
    ],
  ),
   
  SizedBox(height: 12,),
  Apptext('''''Your information, including Personal Data, is processed at the Company'soperating offices and in any other places where the parties involved in theprocessing are located. It means that this information may be transferred to —and maintained on — computers located outside of Your state, province, countryor other governmental jurisdiction where the data protection laws may differthan those from Your jurisdiction.

Your consent to this Privacy Policy followed by Your submission of suchinformation represents Your agreement to that transfer.

The Company will take all steps reasonably necessary to ensure that Your datais treated securely and in accordance with this Privacy Policy and no transferof Your Personal Data will take place to an organization or a country unlessthere are adequate controls in place including the security of Your data andother personal information.
''')
,SizedBox(height: 20,)
  ,Row(
    children: [ 
     
      Apptext("Security of Your Personal Data ",fontSize:16,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
    ],
  ),
  Apptext('''The security of Your Personal Data is important to Us, but remember that nomethod of transmission over the Internet, or method of electronic storage is100% secure. While We strive to use commercially acceptable means to protectYour Personal Data, We cannot guarantee its absolute security.''')
,SizedBox(height: 20,)
  ,Row(
    children: [ 
     
      Apptext("changes to this Privacy Policy",fontSize:16,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
    ],
  ),
SizedBox(height: 12,),
Apptext('''We may update Our Privacy Policy from time to time. We will notify You of anychanges by posting the new Privacy Policy on this page.

We will let You know via email and/or a prominent notice on Our Service, priorto the change becoming effective and update the "Last updated" date at the topof this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes.Changes to this Privacy Policy are effective when they are posted on thispage.''')

,SizedBox(height: 20,)
  ,Row(
    children: [ 
     
      Apptext("Contact Us",fontSize:16,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w500,)
    ],
  ),
  SizedBox(height: 12,)
  ,Apptext('''If you have any questions about this Privacy Policy, You can contact us:  ''',fontSize:20,Colors: Color.fromRGBO(0, 0, 0, 1),fontweight: FontWeight.w300,) ,SizedBox(height: 20,),

        Row(
          children: [
            Apptext(" * By phone number:")
            
          ],
        )

],),
        ),
      ),
    );
  }
}